#!/bin/bash

score=0
max=0

echo "Testes positivos (ficheiros em tests/good/)"

for f in tests/good/*.py; do
    max=`expr $max + 1`;
    echo $f
    expected=tests/good/`basename $f .py`.out
    rm -f out
    if ./mini-python $f > out; then
	if cmp --quiet out $expected; then
	    score=`expr $score + 1`;
	else
	    echo "  FALHA : saida errada para $f"
	fi
    else
	echo "  FALHA da interpretação para $f"
    fi
done
echo

echo "Testes negativos (ficheiros em tests/bad/)"

for f in tests/bad/*.py; do
    max=`expr $max + 1`;
    echo $f
    rm -f out
    if ./mini-python $f > out 2>&1; then
	echo "  FALHA : a avaliação de $f deveria falhar"
    else
        if grep -q "^error:" out; then
	    score=`expr $score + 1`;
        else
            echo "  FALHA : deveria mostrar 'error'"
        fi
    fi
done

echo
percent=`expr 100 \* $score / $max`;
echo "Score: $score / $max tests, soit $percent%"
